import localFont from 'next/font/local'
import Image from 'next/image'
import type { Metadata } from "next";
import "./globals.css";
import { Footer } from './components/footer';
import { QuizProvider } from './context';

const NormsFont = localFont({
  src: '../public/Norms-Regular.otf',
})

export const metadata: Metadata = {
  title: "Manual product quiz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      <body
        className={`${NormsFont.className} antialiased`}
      >
        <QuizProvider>
          <header className='container mx-auto relative px-6 md:px-0'>
            <Image className='absolute py-[30px]' src="/logo.png" width={40} height={40} alt="Manual Logo" />
          </header>
          {children}
          <Footer />
        </QuizProvider>
      </body>
    </html>
  );
}
